server:
  port: 8080
  servlet:
    session:
      timeout: 1800s
  tomcat:
    uri-encoding: UTF-8
    protocol-header: x-forwarded-proto
  use-forward-headers: true

spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com/management/grade/model
  mapper-locations: classpath:mapping/*.xml

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage_sys?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 168168
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  #Redis缓存设置
  redis:
    port: 6379
    host: 127.0.0.1
    #password: 123456
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  cache:
    redis:
      ## Entry expiration in milliseconds. By default the entries never expire.
      time-to-live: 1d
      #写入redis时是否使用键前缀。
      use-key-prefix: true

